name: 🧱 Setup pnpm, install and cache packages
description: Setup pnpm, install and cache packages
icon: package
color: yellow

runs:
  using: "composite"
  steps:
    - name: "Cleanup build folder"
      shell: bash
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - uses: pnpm/action-setup@v3
      with:
        run_install: |
          - recursive: true
            args: [--frozen-lockfile]

    # - name: Get pnpm store directory
    #   id: pnpm-cache
    #   shell: bash
    #   run: |
    #     echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    # - uses: actions/cache@v3
    #   name: Setup pnpm cache
    #   with:
    #     path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
    #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pnpm-store-

    # - run: pnpm install --frozen-lockfile
    #   shell: bash
