name: 🧱 Setup pnpm, install and cache packages
description: Setup pnpm, install and cache packages
icon: package
color: yellow

runs:
  using: 'composite'
  steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - run: pnpm install --frozen-lockfile
      shell: bash
      
